Map<String, String> symbolMap = {
  "coma": ",",
  "dos puntos": ":",
  "punto y coma": ";",
  "punto": ".",
  "tabulación": "\t",
  "espacio": " ",
  "doble espacio": "  ",
  "signo de interrogacion": "?",
  "signo de interrogacion abierto": "¿",
  "signo de interrogacion cerrado": "?",
  "signo de exclamacion": "!",
  "signo de exclamacion abierto": "¡",
  "signo de exclamacion cerrado": "!",
  "arroba": "@",
  "numeral": "#",
  "dólar": "\$",
  "porcentaje": "%",
  "ampersand": "&",
  "asterisco": "*",
  "paréntesis abierto": "(",
  "paréntesis cerrado": ")",
  "corchete abierto": "[",
  "corchete cerrado": "]",
  "llave abierta": "{",
  "llave cerrada": "}",
  "menor que": "<",
  "mayor que": ">",
  "igual": "=",
  "más": "+",
  "menos": "-",
  "guion bajo": "_",
  "barra": "/",
  "barra invertida": "\\",
  "barra vertical": "|",
  "tilde": "~",
  "circunflejo": "^",
  "siguiente línea": "\n",
  "salto de línea": "\n"
};
