import 'package:sonix_text/infrastructure/level_model.dart';
import 'package:uuid/uuid.dart';

final List<LevelModel> listLevel = [
  LevelModel(
      id: Uuid().v4(),
      title: 'Level 1',
      level: 1,
      point: 30,
      multiplier: 1,
      message: '¡Bienvenido! El viaje apenas comienza. 💪',
      isClaimed: false),
  LevelModel(
      id: Uuid().v4(),
      title: 'Level 2',
      level: 2,
      point: 60,
      multiplier: 10,
      message: '¡Sigues avanzando! No te detengas. 🔥',
      isClaimed: false),
  LevelModel(
      id: Uuid().v4(),
      title: 'Level 3',
      level: 3,
      point: 90,
      multiplier: 20,
      message: '¡Increíble! Te estás volviendo un experto. 🏆',
      isClaimed: false),
  LevelModel(
      id: Uuid().v4(),
      title: 'Level 4',
      level: 4,
      point: 120,
      multiplier: 30,
      message: '¡Wow! Tu esfuerzo está dando frutos. 🚀',
      isClaimed: false),
  LevelModel(
      id: Uuid().v4(),
      title: 'Level 5',
      level: 5,
      point: 150,
      multiplier: 50,
      message: '¡Mitad del camino! Mantén el ritmo. 🏃‍♂️',
      isClaimed: false),
  LevelModel(
      id: Uuid().v4(),
      title: 'Level 6',
      level: 6,
      point: 220,
      multiplier: 75,
      message: '¡Eres una máquina de productividad! 🤖',
      isClaimed: false),
  LevelModel(
      id: Uuid().v4(),
      title: 'Level 7',
      level: 7,
      point: 300,
      multiplier: 100,
      message: '¡Nada te detiene! Sigue así. 💯',
      isClaimed: false),
  LevelModel(
      id: Uuid().v4(),
      title: 'Level 8',
      level: 8,
      point: 400,
      multiplier: 150,
      message: '¡Nivel Pro! Eres un crack. 🔥',
      isClaimed: false),
  LevelModel(
      id: Uuid().v4(),
      title: 'Level 9',
      level: 9,
      point: 500,
      multiplier: 200,
      message: '¡Leyenda! Estás a un paso de la grandeza. 🏅',
      isClaimed: false),
  LevelModel(
      id: Uuid().v4(),
      title: 'Level 10',
      level: 10,
      point: 600,
      multiplier: 300,
      message: '¡Maestro absoluto! Lo has logrado. 🎖',
      isClaimed: false),
];
